# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'recordPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Record_Ui_Dialog(object):
    def setupUi(self, Dialog, record_num = 3):
        Dialog.setObjectName("Dialog")
        Dialog.resize(510, 750)
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(150, 0, 211, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(3, 0))
        self.tabWidget.setBaseSize(QtCore.QSize(2, 0))
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setIconSize(QtCore.QSize(127, 20))
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setPointSize(11)
        self.tab.setFont(font)
        self.tab.setObjectName("tab")
        self.tabWidget.addTab(self.tab, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.frame_3=[]
        self.label_3=[]
        self.label_4=[]
        self.pushButton_2=[]

        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(30, 30, 451, 80))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.dateEdit = QtWidgets.QDateEdit(self.frame)
        self.dateEdit.setGeometry(QtCore.QRect(80, 20, 110, 22))
        self.dateEdit.setObjectName("dateEdit")
        self.dateEdit_2 = QtWidgets.QDateEdit(self.frame)
        self.dateEdit_2.setGeometry(QtCore.QRect(240, 20, 110, 22))
        self.dateEdit_2.setObjectName("dateEdit_2")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(350, 50, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(200, 20, 31, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(40, 20, 31, 16))
        self.label_2.setObjectName("label_2")
        self.frame_2 = QtWidgets.QScrollArea(Dialog)
        self.frame_2.setGeometry(QtCore.QRect(20, 170, 481, 491))
        self.frame_2.setFrameShape(QtWidgets.QScrollArea.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QScrollArea.Raised)
        self.frame_2.setObjectName("frame_2")
        y_pos =20
        for index in range(record_num):
            self.frame_3.append(QtWidgets.QFrame(self.frame_2))
            self.frame_3[index].setGeometry(QtCore.QRect(20, y_pos, 441, 241))
            self.frame_3[index].setFrameShape(QtWidgets.QFrame.StyledPanel)
            self.frame_3[index].setFrameShadow(QtWidgets.QFrame.Raised)
            self.frame_3[index].setObjectName("frame_3_{}".format(index))
            self.label_3.append(QtWidgets.QLabel(self.frame_3[index]))
            self.label_3[index].setGeometry(QtCore.QRect(10, 30, 411, 161))
            self.label_3[index].setText("")
            self.label_3[index].setObjectName("label_3_{}".format(index))
            self.label_4.append(QtWidgets.QLabel(self.frame_3[index]))
            self.label_4[index].setGeometry(QtCore.QRect(10, 10, 72, 15))
            self.label_4[index].setObjectName("label_4_{}".format(index))
            self.pushButton_2.append(QtWidgets.QPushButton(self.frame_3[index]))
            self.pushButton_2[index].setGeometry(QtCore.QRect(340, 200, 93, 28))
            self.pushButton_2[index].setObjectName("pushButton_2_{}".format(index))
            y_pos += 261

        self.verticalScrollBar = QtWidgets.QScrollBar(self.frame_2)
        self.verticalScrollBar.setGeometry(QtCore.QRect(460, 0, 16, 491))
        self.verticalScrollBar.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar.setObjectName("verticalScrollBar")
        self.pushButton_3 = QtWidgets.QPushButton(Dialog)
        self.pushButton_3.setGeometry(QtCore.QRect(400, 700, 93, 28))
        self.pushButton_3.setObjectName("pushButton")

        self.retranslateUi(Dialog,record_num)
        self.tabWidget.setCurrentIndex(1)
        self.pushButton_3.clicked.connect(Dialog.navigate_back)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog, record_num=3):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "东门"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("Dialog", "西门"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "南门"))
        self.pushButton.setText(_translate("Dialog", "查询"))
        self.label.setText(_translate("Dialog", "到"))
        self.label_2.setText(_translate("Dialog", "从"))
        for index in range(record_num):
            self.label_4[index].setText(_translate("Dialog", "时间"))
            self.pushButton_2[index].setText(_translate("Dialog", "详情"))
        self.pushButton_3.setText(_translate("Dialog", "返回"))