# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'showPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Show_Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("show")
        Dialog.resize(510, 750)
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(160, 0, 211, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(3, 0))
        self.tabWidget.setBaseSize(QtCore.QSize(2, 0))
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setIconSize(QtCore.QSize(127, 20))
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setPointSize(11)
        self.tab.setFont(font)
        self.tab.setObjectName("tab")
        self.tabWidget.addTab(self.tab, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(20, 30, 461, 201))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(30, 20, 401, 151))
        self.label.setText("")
        self.label.setObjectName("label")
        self.frame_2 = QtWidgets.QFrame(Dialog)
        self.frame_2.setGeometry(QtCore.QRect(20, 275, 461, 541))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.scrollArea = QtWidgets.QScrollArea(self.frame_2)
        self.scrollArea.setGeometry(QtCore.QRect(10, 10, 441, 201))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 439, 199))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_2.setGeometry(QtCore.QRect(20, 20, 391, 141))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_3.setGeometry(QtCore.QRect(0, 0, 72, 15))
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton.setGeometry(QtCore.QRect(320, 170, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(390, 240, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.commandLinkButton = QtWidgets.QCommandLinkButton(Dialog)
        self.commandLinkButton.setGeometry(QtCore.QRect(20, 230, 222, 48))
        self.commandLinkButton.setObjectName("commandLinkButton")
        self.pushButton_3 = QtWidgets.QPushButton(Dialog)
        self.pushButton_3.setGeometry(QtCore.QRect(400, 700, 93, 28))
        self.pushButton_3.setObjectName("pushButton")



        # 假设这段代码位于某个类的定义中

        # QScrollArea 的设置
        self.scrollArea_1 = QtWidgets.QScrollArea(self.frame_2)  # 修改 scrollArea 为 scrollArea_1
        self.scrollArea_1.setGeometry(QtCore.QRect(10, 220, 441, 201))
        self.scrollArea_1.setWidgetResizable(True)
        self.scrollArea_1.setObjectName("scrollArea_1")

        # QScrollArea 的内部 Widget
        self.scrollAreaWidgetContents_1 = QtWidgets.QWidget()  # 修改 scrollAreaWidgetContents 为 scrollAreaWidgetContents_1
        self.scrollAreaWidgetContents_1.setObjectName("scrollAreaWidgetContents_1")
        # 注意：这里不需要设置 scrollAreaWidgetContents_1 的 geometry，因为它会被 QScrollArea 管理

        # 将内部 Widget 设置到 QScrollArea
        self.scrollArea_1.setWidget(self.scrollAreaWidgetContents_1)

        # 为 scrollAreaWidgetContents_1 添加子小部件
        self.label_2_1 = QtWidgets.QLabel(self.scrollAreaWidgetContents_1)  # 修改 label_2 为 label_2_1
        self.label_2_1.setGeometry(QtCore.QRect(20, 20, 391, 141))
        self.label_2_1.setText("")
        self.label_2_1.setObjectName("label_2_1")

        self.label_3_1 = QtWidgets.QLabel(self.scrollAreaWidgetContents_1)  # 修改 label_3 为 label_3_1
        self.label_3_1.setGeometry(QtCore.QRect(0, 0, 72, 15))
        self.label_3_1.setObjectName("label_3_1")

        self.pushButton_1 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_1)  # 修改 pushButton 为 pushButton_1
        self.pushButton_1.setGeometry(QtCore.QRect(320, 170, 93, 28))
        self.pushButton_1.setObjectName("pushButton_1")

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(1)
        self.pushButton_3.clicked.connect(Dialog.navigate_back)  # type: ignore
        self.pushButton.clicked.connect(Dialog.go_msg_1)  # type: ignore
        self.pushButton_1.clicked.connect(Dialog.go_msg_2)  # type: ignore
        self.pushButton_2.clicked.connect(Dialog.go_bigger)  # type: ignore
        self.commandLinkButton.clicked.connect(Dialog.go_record)
        QtCore.QMetaObject.connectSlotsByName(Dialog)


    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "show"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "东门"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("Dialog", "西门"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "南门"))
        self.pushButton_2.setText(_translate("Dialog", "监控放大"))
        self.commandLinkButton.setText(_translate("Dialog", "查看以往监控"))
        self.pushButton_3.setText(_translate("Dialog", "返回"))
        self.label_3.setText(_translate("Dialog", "今日流量"))
        self.pushButton.setText(_translate("Dialog", "详情"))
        self.label_3_1.setText(_translate("Dialog", "本周流量"))
        self.pushButton_1.setText(_translate("Dialog", "详情"))

